// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwB7jcnK2fte20w150pa1nuG0lgR0HETo',
    appId: '1:878288456528:web:5924f243b73697c5727a55',
    messagingSenderId: '878288456528',
    projectId: 'learning-firebase-afloate',
    authDomain: 'learning-firebase-afloate.firebaseapp.com',
    databaseURL: 'https://learning-firebase-afloate-default-rtdb.firebaseio.com',
    storageBucket: 'learning-firebase-afloate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5-UtdAQsO_I3RisuO4GefWm7JWqAEjw',
    appId: '1:878288456528:android:8a991200e85aec3e727a55',
    messagingSenderId: '878288456528',
    projectId: 'learning-firebase-afloate',
    databaseURL: 'https://learning-firebase-afloate-default-rtdb.firebaseio.com',
    storageBucket: 'learning-firebase-afloate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayGeifs32SAR6JIkT60cQM_h8JzudzV4',
    appId: '1:878288456528:ios:4cc4276e91ac856d727a55',
    messagingSenderId: '878288456528',
    projectId: 'learning-firebase-afloate',
    databaseURL: 'https://learning-firebase-afloate-default-rtdb.firebaseio.com',
    storageBucket: 'learning-firebase-afloate.appspot.com',
    iosClientId: '878288456528-8cvv111033anv1rm0ac61oguelvau0se.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookies',
  );
}
